/**
 * covibe cross-ide — 跨 IDE 配置生成
 * 支持 Claude Code / Cursor / Windsurf
 */
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { detect } from './detect.mjs';

export async function crossIde(cwd, args) {
  const ide = args[0];
  if (!ide || !['cursor', 'windsurf', 'all'].includes(ide)) {
    console.log(`
  🎵 covibe cross-ide — 跨 IDE 配置生成

  用法:
    covibe cross-ide cursor      生成 .cursorrules
    covibe cross-ide windsurf    生成 .windsurfrules
    covibe cross-ide all         全部生成
    `);
    return;
  }

  const info = detect(cwd);
  const claudeMd = existsSync(join(cwd, 'CLAUDE.md'))
    ? readFileSync(join(cwd, 'CLAUDE.md'), 'utf8')
    : null;

  if (ide === 'cursor' || ide === 'all') generateCursorRules(cwd, info, claudeMd);
  if (ide === 'windsurf' || ide === 'all') generateWindsurfRules(cwd, info, claudeMd);
}

function generateCursorRules(cwd, info, claudeMd) {
  // 从 CLAUDE.md 提取核心规则，转换为 Cursor 格式
  const rules = buildRules(info, claudeMd);

  const content = `# Cursor Rules — Generated by covibe
# 从项目 CLAUDE.md 自动转换，保持团队规范跨 IDE 一致

${rules}

# 技术栈
- 语言: ${info.language || 'unknown'}
- 框架: ${info.frameworks.join(', ') || 'none'}
${info.commands.test ? `- 测试命令: ${info.commands.test}` : ''}
${info.commands.lint ? `- Lint 命令: ${info.commands.lint}` : ''}

# covibe 团队协作
- 遵守 .claude/harness.team.json 中的 enforced 规则
- 共享经验板: .teamwork/experiences/
- 任务看板: .teamwork/board.json
`;

  writeFileSync(join(cwd, '.cursorrules'), content);
  console.log('  ✅ 生成了 .cursorrules（Cursor AI Rules）');

  // 也生成 .cursor/rules/ 目录格式（Cursor v2）
  const rulesDir = join(cwd, '.cursor/rules');
  mkdirSync(rulesDir, { recursive: true });
  writeFileSync(join(rulesDir, 'covibe.md'), content);
  console.log('  ✅ 生成了 .cursor/rules/covibe.md（Cursor Rules v2）');
}

function generateWindsurfRules(cwd, info, claudeMd) {
  const rules = buildRules(info, claudeMd);

  const content = `# Windsurf Rules — Generated by covibe
# 从项目 CLAUDE.md 自动转换

${rules}

# 技术栈: ${info.language || 'unknown'} / ${info.frameworks.join(', ') || 'none'}
${info.commands.test ? `# 测试: ${info.commands.test}` : ''}
`;

  writeFileSync(join(cwd, '.windsurfrules'), content);
  console.log('  ✅ 生成了 .windsurfrules（Windsurf AI Rules）');
}

function buildRules(info, claudeMd) {
  let rules = [];

  // 从 CLAUDE.md 提取关键规则
  if (claudeMd) {
    const lines = claudeMd.split('\n');
    let inRulesSection = false;
    for (const line of lines) {
      if (line.match(/^##\s*(操作原则|规则|约定|质量|开发|Principles|Rules|Quality)/i)) {
        inRulesSection = true;
        rules.push(line);
        continue;
      }
      if (line.match(/^##\s/) && inRulesSection) {
        inRulesSection = false;
      }
      if (inRulesSection && line.trim()) {
        rules.push(line);
      }
    }
  }

  // 如果 CLAUDE.md 没有提取到规则，生成默认规则
  if (rules.length === 0) {
    rules = [
      '## 开发规则',
      '- 默认全速执行，不需要反复确认',
      '- 先复现再修 bug，禁止猜测性修复',
      '- 每次只改一处，验证后再改下一处',
      '- 禁止交付半成品功能',
      '- 禁止接入假数据',
    ];
  }

  return rules.join('\n');
}
